### ISSUE TITLE
ERROR 1054 (42S22) at line 41: Unknown column 'toolbox_customise_domains.domain_name' in 'field list'

### ISSUE THREAD

**Issue by MrHappy** [gianlucagiacometti/roundcube-postfixadmin-toolbox#1]
Got that error message and had to change the query to create the view to:

> CREATE OR REPLACE VIEW `toolbox_customise_skins_view` AS
  SELECT
    `toolbox_customise_domains`.`domain_name`,
    `toolbox_customise_skins`.`skin`,
    `toolbox_customise_skins`.`customise_blankpage`,
    `toolbox_customise_skins`.`blankpage_type`,
    `toolbox_customise_skins`.`blankpage_image`,
    `toolbox_customise_skins`.`blankpage_url`,
    `toolbox_customise_skins`.`blankpage_custom`,
    `toolbox_customise_skins`.`customise_css`,
    `toolbox_customise_skins`.`additional_css`
  FROM `toolbox_customise_skins`
    LEFT JOIN `toolbox_customise_domains` ON (`toolbox_customise_domains`.`id` = `toolbox_customise_skins`.`toolbox_customise_domain_id`);

After I enabled the toolbox (and only aliases) in roundcube the menu item appears, but the apache-error-log gives me
`PHP Warning:  Invalid argument supplied for foreach() in /usr/share/roundcubemail/program/steps/settings/edit_prefs.inc on line 56`
and the form remains empty.

Any help would be appreciated.

**Comment by gianlucagiacometti** [comment]
MySQL or PostgreSQL?

**Comment by gianlucagiacometti** [comment]
Got it! I forgot 2 fields in table toiolbox_customise_skins in mysql.initial.sql, sorry for that.

**Comment by gianlucagiacometti** [comment]
Fixed!

**Comment by MrHappy** [comment]
> 
> 
> MySQL or PostgreSQL?

MySQL
