### ISSUE TITLE
Setting alias causes MySQL error: "Invalid datetime 'now()'"

### ISSUE THREAD

**Issue by trollkotze** [gianlucagiacometti/roundcube-postfixadmin-toolbox#14]
I just installed the toolbox plugin v1.4.10, using Roundcube v1.4.11, using MySQL v5.7.29.

If I want to set an Alias, I get this MySQL error in the error log:

```[20-Mar-2021 16:40:52 +0100]: <l0ov7hqo> DB Error: [1292] Incorrect datetime value: 'now()' for column 'created' at row 1 (SQL Query: INSERT INTO `alias` (`address`, `goto`, `domain`, `created`, `modified`, `active`) VALUES ('abc@xyz.net', 'def@xyz.net', 'xyz.net', 'now()', 'now()', 'true')) in /var/lib/roundcube/program/lib/Roundcube/rcube_db.php on line 543 (POST /webmail/?_task=settings&_action=plugin.toolbox.save)```

It seems the `now()` function does not generate a valid datetime here. Checking the MySQL docs (even though for v8 and I'm using v5.7) reveals that [the now() function](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_now) returns a date string in a specific format (and indeed it behaves here as described in my old MySQL version), and this is apparently not a valid datetime.

**Comment by gianlucagiacometti** [comment]
Actually, now() and true should be called without ' otherwise they are interpreted as a strings. I will investigate further.
Can you please activate level 2 in debug and check the query called at that specific step, please?

**Comment by trollkotze** [comment]
Here is the error log witg debug level 2:
```
[23-Mar-2021 12:58:05 +0100]: <c9q18eqt> DB Error: [1292] Incorrect datetime value: 'now()' for column 'created' at row 1 (SQL Query: INSERT INTO `alias` (`address`, `goto`, `domain`, `created`, `modified`, `active`) VALUES ('trollkotze@sangham.net', 'moritz@sangham.net', 'sangham.net', 'now()', 'now()', 'true')) in /var/lib/roundcube/program/lib/Roundcube/rcube_db.php on line 543 (POST /webmail/?_task=settings&_action=plugin.toolbox.save)```

It seems that, indeed, 'true'and 'now()' appear within single quotes inside the SQL query.

**Comment by gianlucagiacometti** [comment]
As soon as I have some free time I will set up a test server with mysql and test it
