### ISSUE TITLE
Error when setting vacation message

### ISSUE THREAD

**Issue by trollkotze** [gianlucagiacometti/roundcube-postfixadmin-toolbox#15]
I just installed the toolbox plugin v1.4.10, using Roundcube v1.4.11, using PHP 7.2 and MySQL v5.7.29.

When I want to set a vacation message, after I hit "save", no confirmation appears, and the interface part where I edited the inputs stays empty.
After checking the error log, I find this error being logged every time I try to set a vacation message in RoundCube Toolbox:

```[20-Mar-2021 16:52:14 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function format() on boolean in /var/lib/roundcube/plugins/toolbox/lib/Roundcube/rcube_toolbox_storage_sql_helper.php:170
Stack trace:
#0 /var/www/lib/roundcube/plugins/toolbox/lib/Roundcube/rcube_toolbox_storage_sql.php(744): rcube_toolbox_storage_sql_helper->to_timestamp('19/03/2021', '%d/%m/%Y')
#1 /var/lib/roundcube/plugins/toolbox/toolbox.php(1300): rcube_toolbox_storage_sql->save_tool_data('moritz@sangham....', Array)
#2 /var/lib/roundcube/program/lib/Roundcube/rcube_plugin_api.php(522): toolbox->save()
#3 /var/lib/roundcube/index.php(292): rcube_plugin_api->exec_action('plugin.toolbox....')
#4 {main}
  thrown in /var/lib/roundcube/plugins/toolbox/lib/Roundcube/rcube_toolbox_storage_sql_helper.php on line 170```

**Comment by gianlucagiacometti** [comment]
Fixed through [401a997](https://github.com/gianlucagiacometti/roundcube-toolbox/commit/401a997297d4625e94d066a72ac490891bf6ca6a)
Can you please try? I don't have any installation with MySQL at the moment.

**Comment by trollkotze** [comment]
I applied the change in that commit manually, since I am using Roundcube release v1.4.11, and as I understand the git/development version of the toolbox plugin is only compatible with the git/development version of Roundcube.

Now I get this SQL error when trying to set a vacation message:
```23-Mar-2021. 13:06:13 +0100]: <c9q18eqt> DB Error: [1364] Field 'email' doesn't have a default value (SQL Query: INSERT INTO vacation (active, activefrom, activeuntil, interval_time, subject, body, modified, created) VALUES (false,'2021-03-22 13:06:13','2021-03-24 13:06:13',0,'Test','Test',now(),now())) in /var/lib/roundcube/program/lib/Roundcube/rcube_db.php on line 543 (POST /webmail/?_task=settings&_action=plugin.toolbox.save)```

This error seems reasonable. Of course the e-mail address should not be missing in the SQL db insert when setting a vacation message for one specific e-mail address.

**Comment by gianlucagiacometti** [comment]
Actually, the only difference between the last Release and the git version is described in [https://github.com/gianlucagiacometti/roundcube-toolbox/pull/8](https://github.com/gianlucagiacometti/roundcube-toolbox/pull/8)
As soon as you check rcmail_action:: (I don't know if it's already in an official RC release) and change according with your installation the git version of toolbox is fine

**Comment by wildstray** [comment]
Hello, I'm encountered the same issue with NULL email field in INSERT, so I cannot save (RC 1.4.11, toolbox 1.4.10.1 and already manual fixed https://github.com/gianlucagiacometti/roundcube-toolbox/commit/401a997297d4625e94d066a72ac490891bf6ca6a). No way, the email in that INSERT is mandatory (where did it get lost?).

**Comment by wildstray** [comment]
I dunno if I must open a new ticket but I noticed that preview and attachments show blank page, only a "Save" button with no settings at all...

**Comment by gianlucagiacometti** [comment]
I currently use PostgresSQL, please, give me a couple of days to install a test version with MySQL. I guess I must fix a couple of things in the MySQL DB.
