### ISSUE TITLE
Missing end of line and installation

### ISSUE THREAD

**Issue by tomasbrchan** [gianlucagiacometti/roundcube-postfixadmin-toolbox#16]
Hello,
thank you for great plugin. I just installed it and I had to deal with 2 issues:
config.inc.php.dist on line 202 "$config['toolbox_use_postfixadmin_domain_admins'] = true" missing ';' and the end of line. During install it is copied to live and creates error.

During install it is installed into folder 'roundcube_toolbox'. When I enabled plugin 'roucube_toolbox" error appeared, because it looked for 'roundube_toolbox.php'. I had to rename folder into 'toolbox', change in config file. I do not know if I did something wrong, it does not seem to me. It can cause some troubles in future with upgrade, I do not know.

Have a nice day
Tomas

**Comment by gianlucagiacometti** [comment]
Thank you very much. I fixed the typo and added a line to the readme file.
The folder name of the plugin must be toolbox
Fixed through https://github.com/gianlucagiacometti/roundcube-toolbox/commit/2223180da5e29ad3eaf5c44ab66d06fc01b71435 and https://github.com/gianlucagiacometti/roundcube-toolbox/commit/a59e9a994a608da93f263a3be0d0e0b5e0e76a4b
