### ISSUE TITLE
Database connect error, but don't want to use DB

### ISSUE THREAD

**Issue by f-zappa** [gianlucagiacometti/roundcube-postfixadmin-toolbox#18]
Hi,
as soon as I enable the plugin, roundcube throws db errors like the following:

[13-Aug-2021 12:13:53 +0000]: <1c68b788> DB Error: SQLSTATE[08006] [7] could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Network unreachable
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432? (POST /?_task=mail&_action=refresh)

I am using the recent docker-container using sqlite (there will be ~5 users, so sqlite should do). At the moment I only want to use the "purge" tool and hope that this will not need a database connection. My configuration now looks like this:

$config['plugins'] = array_filter(array_unique(array_merge($config['plugins'], ['toolbox'])));
$config['toolbox_tools'] = [ 'purge' ];
$config['toolbox_roundcube_dsnw'] = 'sqlite:////var/roundcube/db/sqlite.db?mode=0646';
$config['toolbox_postfix_dsnrw'] = '';

Any chance to get it running?

Regards, Uli

**Comment by gianlucagiacometti** [comment]
Purge indeed use a DB connection
