### ISSUE TITLE
New install issues and notes; RM 1.5, Postfix, Postfixadmin, Dovecot, MySQL

### ISSUE THREAD

**Issue by RickOSidhe** [gianlucagiacometti/roundcube-postfixadmin-toolbox#19]
1. The project documentation and config.php.conf.dist are a bit out-of-sync. Project installation states $rcmail_config['toolbox_dsn']'must be set. Toolbox didn't appear to read that var at all. Set $config['toolbox_postfix_dsnw'] instead, per config file comments, and it worked. Docs should also point out that the dsn for Roundcube needs to be set, which is buried in the middle of the config rather than placed at the top with the Postfix/Postfixadmin dsn

2. Docs are unclear which db the user should create the toolbox tables in. Probably help some folks to explicitly state that the tables need to be added to the Roundcube db rather than Postfixadmin db.

3. Alias issue: SQL inserts fail due to invalid timestamp. Disabling strict mode on the MySQL server is a workaround, but the creation and modification dates making the insert are invalid 0000-00-00 00:00:00. Log shows Now() for the timestamp in the SQL, but it's not making it into the db.

4. Alias issue: 'Enabled' boolean not reflecting correctly in Toolbox. I have verified that toggling active is actually reflecting correctly in the db - the problem is that the Roundcube:alias:active field is not being shown correctly by toolbox.

**Comment by RickOSidhe** [comment]
** relevant log entries - emails and aliases redacted

INSERT INTO `alias` (`address`, `goto`, `domain`, `created`, `modified`, `active`) VALUES ('alias@domain.tld', 'mailbox@domain.tld', 'domain.tld', 'now()', 'now()', 'true')

UPDATE `alias` SET `active` = NOT `active` WHERE `address` = 'alias@domain.tld' AND `goto` = 'mailbox@domain.tld'

**Comment by gianlucagiacometti** [comment]
Thank you, I'll have a look ASAP
