### ISSUE TITLE
Failed to load plugin file roundcube_toolbox.php

### ISSUE THREAD

**Issue by Henri-J-Norden** [gianlucagiacometti/roundcube-postfixadmin-toolbox#20]
Hello, I am trying to install this plugin but I am not sure what I'm doing wrong. 
I just updated Roundcube to version 1.5.0, updated the composer packages and everything else seems to be working, so I added this plugin with: 

     composer require gianlucagiacometti/roundcube-toolbox:dev-master

It doesn't show up under About->Installed plugins, though, so I checked errors.log and could see the following error:

    PHP Error: Failed to load plugin file plugins/roundcube_toolbox/roundcube_toolbox.php in program/lib/Roundcube/rcube_plugin_api.php on line 193 (POST /mail/?_task=mail&_action=refresh)

I do not understand why its looking for `roundcube_toolbox.php` instead of `toolbox.php`. 
I tested renaming both the file `toolbox.php` to `roundcube_toolbox.php` and the class `toolbox` to `roundcube_toolbox` - the plugin then loads, but Roundcube stops working entirely (even with what should be working settings in `plugins/roundcube_toolbox/config.inc.php`):
    
     DB Error: could not find driver in /opt/www/roundcubemail-1.5.0/program/lib/Roundcube/rcube_db.php on line 194 (GET /mail/?_task=mail)
     DB Error: could not find driver (GET /mail/?_task=mail)

I'm using composer version 2.1.8, roundcube/plugin-installer 0.3.1

**Comment by gianlucagiacometti** [comment]
Hello,
I do not use plugin manager, so I cannot help you with that.
Just copy the plugin under plugin/toolbox folder, list the plugin in roundcube config file, set up your toolbox configuration file and check.
If it does not work please check the logs and please report the errors.

**Comment by Henri-J-Norden** [comment]
Ah yes, it does work the way you described without the plugin manager. I guess the main issue with the manager is that the directory isn't named "toolbox" automatically when its installed using composer.

**Comment by Henri-J-Norden** [comment]
Ah yes, it does work the way you described without the plugin manager. I guess the main issue with the manager is that the directory isn't named "toolbox" automatically when its installed using composer.
