### ISSUE TITLE
Mysql error while initial sql  script setup.

### ISSUE THREAD

**Issue by boriska2005** [gianlucagiacometti/roundcube-postfixadmin-toolbox#3]
Hi, 

i have folowing error while running initial script and don't understand how to resolve it :
[ #mysql -u user roundcubemail < mysql.initial.sql ]

ERROR 1054 (42S22) at line 43: Unknown column 'toolbox_customise_domains.domain_name' in 'field list'

please help me.

Centos 7, mysql  Ver 14.14 Distrib 5.7.31, for Linux (x86_64)

**Comment by gianlucagiacometti** [comment]
Confirmed. I'll have a look ASAP

**Comment by gianlucagiacometti** [comment]
I updated the sql file with the correct syntax. I guess you already have the 2 tables in the db, so just run the "create view" section (otherwise you will get an error for already existing tables).

**Comment by gianlucagiacometti** [comment]
Fixed via #[13ea5d5](https://github.com/gianlucagiacometti/roundcube-toolbox/commit/13ea5d56ce1d45af8df29a7c2d968727dba71126)

**Comment by boriska2005** [comment]
Thank you for quick answer and quick resolve problem.
