### ISSUE TITLE
Roundcube 1.4.10 - plugin uninstallable because roundcube/plugin-installer is 0.2.0

### ISSUE THREAD

**Issue by SinyaWeo** [gianlucagiacometti/roundcube-postfixadmin-toolbox#6]
In composer.json is roundcube/plugin-installer required in version 0.1.6, but Roundcube 1.4.10 uses version 0.2.0 and that renders your plugin unistallable.

Milan

**Comment by gianlucagiacometti** [comment]
Should be fixed with last commit #2d425ab
